name: uwnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - dask
  - xarray
  - matplotlib
  - ipython
  - jupyterlab
  - cython
  - torchvision
  - pytorch
  - attrs
  - scikit-learn
  - pip
  - pip:
      - git+https://github.com/nbren12/gnl@master#subdirectory=python
      - tqdm
      - snakemake
      - metpy
      - flake8
      - f90nml
