name: uw-machine-learning
channels:
  - soumith
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - dask
  - xarray
  - scikit-learn
  - matplotlib
  - holoviews
# bokeh stuff
  - bokeh
  - selenium
  - phantomjs
  - datashader
  - ipython
  - jupyter
  - cython
  - attrs
  - pip
  - pip:
      - git+https://github.com/nbren12/gnl@master#subdirectory=python/gnl
      - git+https://github.com/nbren12/gnl@master#subdirectory=python/xnoah
      - snakemake==4.0
      - tqdm
      - http://download.pytorch.org/whl/torch-0.2.0.post3-cp36-cp36m-macosx_10_7_x86_64.whl
      - pyro-ppl
      - pytest-regtest
