name: nn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - dask
  - xarray
  - matplotlib
  - ipython
  - jupyter
  - cython
  - torchvision 
  - cuda90 
  - seaborn
  - pytorch
  - attrs
  - pip
  - pip:
      - git+https://github.com/nbren12/gnl@master#subdirectory=python/gnl
      - git+https://github.com/nbren12/gnl@master#subdirectory=python/xnoah
      - snakemake
      - tqdm
      - pytest-regtest
