name: nn_atmos_param
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy=1.13
  - dask=0.17
  - xarray=0.10
  - matplotlib=2.2
  - ipython=6.2
  - jupyter=1.0
  - cython=0.27
  - torchvision=0.1
  - seaborn=0.8
  - pytorch=0.3
  - attrs
  - pip
  - pip:
      - git+https://github.com/nbren12/gnl@v0.1#subdirectory=python/gnl
      - git+https://github.com/nbren12/gnl@v0.1#subdirectory=python/xnoah
      - snakemake
      - tqdm
