version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t test-uwnet-image .
     # run tests
     - run: |
        docker run -w /opt/uwnet -v $PWD:/opt/uwnet test-uwnet-image pytest
        docker run -w /opt/uwnet -v $PWD:/opt/uwnet test-uwnet-image tests/test_sam_nn_integration_in_docker.sh
